//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sikongqi
{
    using System;
    using System.Collections.Generic;
    
    public partial class sikongqi
    {
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string @operator { get; set; }
        public Nullable<int> planNumber { get; set; }
        public Nullable<int> result { get; set; }
        public Nullable<int> finalNumber { get; set; }
        public Nullable<System.DateTime> wrongTime { get; set; }
        public int id { get; set; }
    }
}
